### ISSUE TITLE
Options in example are missing from full list

### ISSUE THREAD

**Issue by vchske** [ibekso/medium#3]
Hello. It looks like the options "EnableArmOnSelection" and "_PluginAutoPopulateThreshold" are missing from the full_options_list as well as both live 11 lists. Is this an oversight? Or are these options no longer available?

**Comment by frankois** [comment]
Thanks a lot for pointing this out, it was indeed an oversight.

Those options are definitely available in live 11, as described in this [article](https://medium.com/@ibekso/how-to-expand-ableton-with-options-txt-788e7b9c8020).
